name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-rdma:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: make
        run: |
          apt-get update && apt-get install -y build-essential
          apt search linux-headers-`uname -r`
          make -C rxe rxe
          sudo modprobe rdma_cm udp_tunnel ip6_udp_tunnel ib_uverbs
          sudo lsmod
          sudo insmod -f ./rxe/rdma_rxe.ko; ls
          sudo dmesg
          sudo rdma link add rxe0 type rxe netdev `ip a | grep -E "^2: " | tr ":" " " | awk '{print $2}'`
          ls /sys/class/infiniband
